import { useEffect, useState, type ReactNode } from "react";
import { AlertTriangle, ArrowLeft, Boxes, Building2, CheckCircle2, Database, ExternalLink, FolderOpen, LoaderCircle, MapPinned, PackageOpen, RefreshCw, Route, Store } from "lucide-react";

import { ThailandDeliveryMap } from "../../components/do-delivery/ThailandDeliveryMap";
import { doDeliveryService } from "../../services/doDeliveryService";
import type { DoAnalyticsResult, DoBranchMasterResult, DoBranchMasterSaveResult, DoDeliveryResult, DoDeliverySaveResult } from "../../types/doDelivery.types";

const fmt = (value: number) => new Intl.NumberFormat("th-TH", { maximumFractionDigits: 2 }).format(value);
const nameOf = (path: string) => path.split(/[\\/]/).pop() || path;

export function DoDeliveryPage({ onBack }: { onBack: () => void }) {
  const [pdfPaths, setPdfPaths] = useState<string[]>([]), [result, setResult] = useState<DoDeliveryResult | null>(null), [saved, setSaved] = useState<DoDeliverySaveResult | null>(null);
  const [masterPath, setMasterPath] = useState(""), [master, setMaster] = useState<DoBranchMasterResult | null>(null), [masterSaved, setMasterSaved] = useState<DoBranchMasterSaveResult | null>(null);
  const [overview, setOverview] = useState<DoAnalyticsResult | null>(null), [regionData, setRegionData] = useState<DoAnalyticsResult | null>(null), [detail, setDetail] = useState<DoAnalyticsResult | null>(null);
  const [selectedRegion, setSelectedRegion] = useState(""), [selectedProvince, setSelectedProvince] = useState(""), [period, setPeriod] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState("");

  const filters = (value = period) => { if (!value) return {}; const [year, month] = value.split("-").map(Number); return { year, month }; };
  const loadOverview = async (value = period) => { const data = await doDeliveryService.analytics(filters(value)); setOverview(data); setDetail(data); setRegionData(null); setSelectedRegion(""); setSelectedProvince(""); };
  useEffect(() => { void loadOverview("").catch(() => undefined); }, []);
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(""); try { await work(); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } };

  const selectMaster = async () => { const path = await doDeliveryService.selectMasterFile(); if (path) { setMasterPath(path); setMaster(null); setMasterSaved(null); } };
  const selectPdfs = async () => { const paths = await doDeliveryService.selectPdfFiles(); if (paths.length) { setPdfPaths(paths); setResult(null); setSaved(null); } };
  const selectRegion = (region: string) => run(async () => { if (region === selectedRegion) { setSelectedRegion(""); setSelectedProvince(""); setRegionData(null); setDetail(overview); return; } const data = await doDeliveryService.analytics({ ...filters(), region }); setSelectedRegion(region); setSelectedProvince(""); setRegionData(data); setDetail(data); });
  const selectProvince = (province: string) => run(async () => { const data = await doDeliveryService.analytics({ ...filters(), region: selectedRegion, province }); setSelectedProvince(province); setDetail(data); });
  const shown = detail || overview;

  return <div className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8 lg:py-9">
    <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-l-4 border-teal-500 px-7 py-7"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm font-semibold text-cyan-700"><ArrowLeft size={17} /> กลับเมนูลงยอด</button><div className="mt-7 flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><MapPinned size={27} /></span><div><p className="text-[10px] font-semibold tracking-[.24em] text-teal-600">DO DELIVERY ANALYTICS</p><h2 className="mt-1 text-3xl font-bold text-slate-900">วิเคราะห์ยอดจัดส่ง DO</h2><p className="text-sm text-slate-500">นำเข้า Master อ่านใบคุมส่ง และวิเคราะห์พื้นที่แบบโต้ตอบ</p></div></div></div></section>

    <section className="mt-6 grid gap-5 xl:grid-cols-2">
      <UploadCard title="1. Master ข้อมูลสาขา" description="นำเข้าครั้งแรกหรือเมื่อมีรายชื่อสาขาใหม่" icon={Database} action={selectMaster} actionLabel={masterPath ? "เลือก Master ใหม่" : "เลือกไฟล์ Master (.xlsx)"} selected={masterPath ? nameOf(masterPath) : ""}>
        <button disabled={!masterPath || busy} onClick={() => run(async () => setMaster(await doDeliveryService.previewMaster(masterPath)))} className="rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">ตรวจสอบ Master</button>
        <button disabled={!master || busy} onClick={() => run(async () => { if (!master) return; setMasterSaved(await doDeliveryService.saveMaster(master)); await loadOverview(); })} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">อัปเดตข้อมูลสาขา</button>
      </UploadCard>
      <UploadCard title="2. ไฟล์ ReportDOByRoute" description="แนะนำ Excel (.xls) อ่านเร็วและแม่นกว่า • PDF ใช้สำรองได้" icon={PackageOpen} action={selectPdfs} actionLabel={pdfPaths.length ? `เลือกแล้ว ${pdfPaths.length} ไฟล์` : "เลือกไฟล์ DO (.xls หรือ .pdf)"} selected={pdfPaths.map(nameOf).join(", ")}>
        <button disabled={!pdfPaths.length || busy} onClick={() => run(async () => setResult(await doDeliveryService.preview({ pdfPaths })))} className="rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">ประมวลผลและ Preview</button>
        <button disabled={!result || busy} onClick={() => run(async () => { if (!result) return; setSaved(await doDeliveryService.save(result)); await loadOverview(); })} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">บันทึกฐานข้อมูล DO</button>
      </UploadCard>
    </section>

    {busy ? <Notice icon={<LoaderCircle className="animate-spin" size={19} />} tone="blue">กำลังประมวลผล กรุณารอสักครู่</Notice> : null}
    {error ? <Notice icon={<AlertTriangle size={19} />} tone="red">{error}</Notice> : null}
    {master ? <Notice icon={<CheckCircle2 size={19} />} tone="indigo">Master พร้อมนำเข้า {fmt(master.branch_count)} สาขา • {master.province_count} จังหวัด • ตัดซ้ำ {master.duplicate_count} แถว • ขัดแย้ง {master.conflict_count}</Notice> : null}
    {masterSaved ? <Success text={`อัปเดต Master ${fmt(masterSaved.branchCount)} สาขา • เติมพื้นที่ให้ DO เดิม ${fmt(masterSaved.updatedDoRows)} แถว`} url={masterSaved.spreadsheetUrl} /> : null}
    {saved ? <Success text={`บันทึก ${fmt(saved.insertedCount)} รายการ • ไฟล์ซ้ำ ${saved.duplicateFileCount} • รอจับคู่ ${saved.unresolvedBranchCount} สาขา`} url={saved.spreadsheetUrl} /> : null}

    {result ? <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Boxes} label="ยอด Preview" value={`${fmt(result.total_quantity)} ชิ้น`} /><Metric icon={Store} label="สาขา" value={fmt(result.branch_count)} /><Metric icon={PackageOpen} label="สินค้า" value={fmt(result.product_count)} /><Metric icon={Building2} label="คลัง" value={fmt(result.warehouses.length)} /><Metric icon={Route} label="รายการ" value={fmt(result.record_count)} /></section> : null}

    <section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-col justify-between gap-4 border-b border-slate-200 px-6 py-5 lg:flex-row lg:items-center"><div><p className="text-[10px] font-bold tracking-[.22em] text-teal-600">INTERACTIVE DELIVERY MAP</p><h3 className="mt-1 text-xl font-bold text-slate-900">แผนที่ยอดจัดส่งประเทศไทย</h3><p className="text-xs text-slate-500">กดภาคบนแผนที่ แล้วเลือกจังหวัดเพื่อดูอันดับสาขา</p></div><div className="flex gap-2"><select value={period} onChange={(event) => run(async () => { setPeriod(event.target.value); await loadOverview(event.target.value); })} disabled={busy} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm"><option value="">ทุกเดือน</option>{overview?.periods.map((item) => <option key={`${item.year}-${item.month}`} value={`${item.year}-${item.month}`}>{item.label}</option>)}</select><button onClick={() => run(() => loadOverview())} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16} /> รีเฟรช</button></div></div>
      {shown ? <><div className="grid gap-4 border-b border-slate-100 p-6 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Boxes} label="ยอดจัดส่ง" value={`${fmt(shown.totalQuantity)} ชิ้น`} /><Metric icon={Store} label="สาขา" value={fmt(shown.branchCount)} /><Metric icon={MapPinned} label="จังหวัด" value={fmt(shown.provinceCount)} /><Metric icon={PackageOpen} label="สินค้า" value={fmt(shown.productCount)} /></div><div className="grid gap-8 p-6 xl:grid-cols-[.8fr_1.2fr]">
        <div><ThailandDeliveryMap regions={overview?.regions || []} selectedRegion={selectedRegion} onSelectRegion={selectRegion} /><button onClick={() => selectRegion("ต่างประเทศ (ลาว)")} className={`mt-4 w-full rounded-xl border px-4 py-2.5 text-sm font-semibold ${selectedRegion === "ต่างประเทศ (ลาว)" ? "border-teal-700 bg-teal-700 text-white" : "border-slate-200 text-slate-600"}`}>ต่างประเทศ (ลาว)</button></div>
        <div><div className="flex flex-wrap items-center gap-2"><button onClick={() => run(() => loadOverview(period))} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">ประเทศไทย</button>{selectedRegion ? <><span>›</span><span className="rounded-full bg-teal-50 px-3 py-1.5 text-xs font-semibold text-teal-700">{selectedRegion}</span></> : null}{selectedProvince ? <><span>›</span><span className="rounded-full bg-teal-700 px-3 py-1.5 text-xs font-semibold text-white">{selectedProvince}</span></> : null}</div>
          {selectedRegion && regionData ? <div className="mt-4 flex flex-wrap gap-2">{regionData.provinces.map((item) => <button key={item.province} onClick={() => selectProvince(item.province)} className={`rounded-xl border px-3 py-2 text-xs ${selectedProvince === item.province ? "border-teal-700 bg-teal-700 text-white" : "border-slate-200 text-slate-600"}`}>{item.province} <b>{fmt(item.quantity)}</b></button>)}</div> : <RegionSummary regions={overview?.regions || []} onSelect={selectRegion} />}
          <Ranking title={selectedProvince ? `10 สาขาสูงสุด จังหวัด${selectedProvince}` : selectedRegion ? `10 สาขาสูงสุด ${selectedRegion}` : "10 สาขาที่รับสินค้าสูงสุด"} rows={shown.topBranches.slice(0, 10).map((item) => ({ code: item.branchCode, name: `${item.branchName} • ${item.province}`, value: item.quantity }))} />
        </div></div></> : <div className="p-12 text-center text-sm text-slate-500">ยังไม่มีข้อมูล DO ใน Google Sheet</div>}
    </section>
  </div>;
}

function UploadCard({ title, description, icon: Icon, action, actionLabel, selected, children }: { title: string; description: string; icon: typeof Database; action: () => void; actionLabel: string; selected: string; children: ReactNode }) { return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><Icon size={21} /></span><div><h3 className="font-bold text-slate-900">{title}</h3><p className="text-xs text-slate-500">{description}</p></div></div><button onClick={action} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-teal-200 bg-teal-50/50 px-5 py-6 text-sm font-semibold text-teal-700"><FolderOpen size={19} /> {actionLabel}</button>{selected ? <p className="mt-3 truncate text-xs text-slate-500">{selected}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{children}</div></div>; }
function Notice({ icon, tone, children }: { icon: ReactNode; tone: "blue" | "red" | "indigo"; children: ReactNode }) { const style = { blue: "border-blue-200 bg-blue-50 text-blue-700", red: "border-red-200 bg-red-50 text-red-700", indigo: "border-indigo-200 bg-indigo-50 text-indigo-800" }[tone]; return <div className={`mt-5 flex items-center gap-3 rounded-2xl border p-4 text-sm ${style}`}>{icon}{children}</div>; }
function Success({ text, url }: { text: string; url: string }) { return <div className="mt-5 flex justify-between gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800"><span className="flex gap-2"><CheckCircle2 size={20} />{text}</span><button onClick={() => doDeliveryService.openSpreadsheet(url)} className="inline-flex items-center gap-2 font-semibold"><ExternalLink size={16} /> เปิด Google Sheet</button></div>; }
function Metric({ icon: Icon, label, value }: { icon: typeof Boxes; label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon size={19} className="text-teal-600" /><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div>; }
function RegionSummary({ regions, onSelect }: { regions: DoAnalyticsResult["regions"]; onSelect: (region: string) => void }) { return <div className="mt-5 grid gap-2 sm:grid-cols-2">{regions.map((item) => <button key={item.region} onClick={() => onSelect(item.region)} className="rounded-2xl border border-slate-100 p-4 text-left hover:border-teal-300"><p className="text-xs text-slate-500">{item.region}</p><p className="mt-1 text-lg font-bold">{fmt(item.quantity)} ชิ้น</p><p className="text-[11px] text-slate-400">{item.provinceCount} จังหวัด • {fmt(item.branchCount)} สาขา</p></button>)}</div>; }
function Ranking({ title, rows }: { title: string; rows: { code: string; name: string; value: number }[] }) { const max = Math.max(...rows.map((row) => row.value), 1); return <div className="mt-5"><h4 className="font-bold">{title}</h4><div className="mt-3 space-y-2">{rows.map((row, index) => <div key={`${row.code}-${index}`} className="rounded-2xl border border-slate-100 p-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-teal-50 text-xs font-bold text-teal-700">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-sm font-semibold">{row.name}</p><p className="text-sm font-bold text-teal-700">{fmt(row.value)}</p></div><p className="text-[11px] text-slate-400">{row.code}</p><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500" style={{ width: `${row.value / max * 100}%` }} /></div></div></div></div>)}</div></div>; }
